Update for Process 2023, Director-free. Would close #97
w3c/wg-effectiveness pull request #98
Opened 2023-10-24 20:28 UTC by svgeesus

- Replaced mentions of The Director with the Team, W3C Decision, as appropriate.
 - Added W3C Council
 - Added Team oversight by W3C Board of Directors

2023-10-24 21:29 UTC, plehegar requested changes
Some minor changes, otherwise LGTM.

2023-10-24 21:29 UTC, plehegar commented on process.md
> +A set of group members may appeal a group decision. The group should first register their opinion with the chair and team contact, and then rasie a **Group Decision Appeal** which requests a [W3C Cou
```suggestion
A set of group members may appeal a group decision. The group should first register their opinion with the chair and team contact, and then raise a **Group Decision Appeal** which requests a [W3C Council](#w3c-council) to review the decision. For more information please see the [W3C Process Document](https://www.w3.org/Consortium/Process/#WGAppeals).
```

2023-10-24 21:29 UTC, plehegar commented on process.md
> +The Working Group will then notify their [Team Contact](#the-w3c-team) to request that the Team notifies the AC of the review period. The AC Review Period is at least 28 days and is 10 days after an
```suggestion
The Working Group will then notify their [Team Contact](#the-w3c-team) to request that the Team notifies the AC of the review period. The AC Review Period is at least 28 days and is 10 days after an Exclusion Opportunity (detailed in the [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy/#sec-exclude-mech). 
```

2023-10-25 08:56 UTC, koalie approved these changes

2023-10-25 12:57 UTC, merged